# v2rayA —— 基于 Web 的 V2Ray/Xray 客户端管理面板
# 官方镜像 mzz2017/v2raya，需特权模式注入防火墙规则
# https://v2raya.org/docs/prologue/installation/docker/
services:
  v2raya:
    image: mzz2017/v2raya
    restart: always
    # privileged: true
    # network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
      # - V2RAYA_NFTABLES_SUPPORT=off
      # - IPTABLES_MODE=legacy
    # volumes:
      # - /lib/modules:/lib/modules:ro
      # - /etc/resolv.conf:/etc/resolv.conf
      # - /etc/v2raya:/etc/v2raya
    ports:
      - "2017:2017"
      - "20170-20172:20170-20172"
    networks:
      - frontend
    dns:
      - 8.8.8.8
      - 114.114.114.114
