#! /bin/bash

laradock_path=/var/www/laradock

laradock_cmd ()
{
        cd $laradock_path
        docker compose -f docker-compose.yml -f docker-compose.custom.yml $@
}

case $@ in
    up)
        laradock_cmd up -d mysql redis workspace php-fpm nginx
        ;;
    wp)
        laradock_cmd exec workspace bash
        ;;
    *)
        laradock_cmd $@

esac
